
Sub AutoTextCongress()

Dim oAutoText As AutoTextEntry

Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Alexander, Lamar", Range:=Selection.Range)
	oAutoText.Value = "Sen. Lamar Alexander (R-TN)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Baldwin, Tammy", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tammy Baldwin (D-WI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Barrasso, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Barrasso (R-WY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Bennet, Michael", Range:=Selection.Range)
	oAutoText.Value = "Sen. Michael Bennet (D-CO)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Blackburn, Marsha", Range:=Selection.Range)
	oAutoText.Value = "Sen. Marsha Blackburn (R-TN)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Blumenthal, Richard", Range:=Selection.Range)
	oAutoText.Value = "Sen. Richard Blumenthal (D-CT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Blunt, Roy", Range:=Selection.Range)
	oAutoText.Value = "Sen. Roy Blunt (R-MO)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Booker, Cory", Range:=Selection.Range)
	oAutoText.Value = "Sen. Cory Booker (D-NJ)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Boozman, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Boozman (R-AR)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Braun, Mike", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mike Braun (R-IN)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Brown, Sherrod", Range:=Selection.Range)
	oAutoText.Value = "Sen. Sherrod Brown (D-OH)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Burr, Richard", Range:=Selection.Range)
	oAutoText.Value = "Sen. Richard Burr (R-NC)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cantwell, Maria", Range:=Selection.Range)
	oAutoText.Value = "Sen. Maria Cantwell (D-WA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Capito, Shelley", Range:=Selection.Range)
	oAutoText.Value = "Sen. Shelley Capito (R-WV)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cardin, Benjamin", Range:=Selection.Range)
	oAutoText.Value = "Sen. Benjamin Cardin (D-MD)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Carper, Thomas", Range:=Selection.Range)
	oAutoText.Value = "Sen. Thomas Carper (D-DE)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Casey, Bob", Range:=Selection.Range)
	oAutoText.Value = "Sen. Bob Casey (D-PA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cassidy, Bill", Range:=Selection.Range)
	oAutoText.Value = "Sen. Bill Cassidy (R-LA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Collins, Susan", Range:=Selection.Range)
	oAutoText.Value = "Sen. Susan Collins (R-ME)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Coons, Christopher", Range:=Selection.Range)
	oAutoText.Value = "Sen. Christopher Coons (D-DE)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cornyn, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Cornyn (R-TX)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cortez Masto, Catherine", Range:=Selection.Range)
	oAutoText.Value = "Sen. Catherine Cortez Masto (D-NV)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cotton, Tom", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tom Cotton (R-AR)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cramer, Kevin", Range:=Selection.Range)
	oAutoText.Value = "Sen. Kevin Cramer (R-ND)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Crapo, Michael", Range:=Selection.Range)
	oAutoText.Value = "Sen. Michael Crapo (R-ID)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Cruz, Ted", Range:=Selection.Range)
	oAutoText.Value = "Sen. Ted Cruz (R-TX)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Daines, Steve", Range:=Selection.Range)
	oAutoText.Value = "Sen. Steve Daines (R-MT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Duckworth, Tammy", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tammy Duckworth (D-IL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Durbin, Richard", Range:=Selection.Range)
	oAutoText.Value = "Sen. Richard Durbin (D-IL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Enzi, Michael", Range:=Selection.Range)
	oAutoText.Value = "Sen. Michael Enzi (R-WY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Ernst, Joni", Range:=Selection.Range)
	oAutoText.Value = "Sen. Joni Ernst (R-IA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Feinstein, Dianne", Range:=Selection.Range)
	oAutoText.Value = "Sen. Dianne Feinstein (D-CA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Fischer, Deb", Range:=Selection.Range)
	oAutoText.Value = "Sen. Deb Fischer (R-NE)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Gardner, Cory", Range:=Selection.Range)
	oAutoText.Value = "Sen. Cory Gardner (R-CO)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Gillibrand, Kirsten", Range:=Selection.Range)
	oAutoText.Value = "Sen. Kirsten Gillibrand (D-NY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Graham, Lindsey", Range:=Selection.Range)
	oAutoText.Value = "Sen. Lindsey Graham (R-SC)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Grassley, Charles", Range:=Selection.Range)
	oAutoText.Value = "Sen. Charles Grassley (R-IA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Harris, Kamala", Range:=Selection.Range)
	oAutoText.Value = "Sen. Kamala Harris (D-CA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Hassan, Margaret", Range:=Selection.Range)
	oAutoText.Value = "Sen. Margaret Hassan (D-NH)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Hawley, Joshua", Range:=Selection.Range)
	oAutoText.Value = "Sen. Joshua Hawley (R-MO)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Heinrich, Martin", Range:=Selection.Range)
	oAutoText.Value = "Sen. Martin Heinrich (D-NM)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Hirono, Mazie", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mazie Hirono (D-HI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Hoeven, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Hoeven (R-ND)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Hyde-Smith, Cindy", Range:=Selection.Range)
	oAutoText.Value = "Sen. Cindy Hyde-Smith (R-MS)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Inhofe, James", Range:=Selection.Range)
	oAutoText.Value = "Sen. James Inhofe (R-OK)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Isakson, Johnny", Range:=Selection.Range)
	oAutoText.Value = "Sen. Johnny Isakson (R-GA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Johnson, Ron", Range:=Selection.Range)
	oAutoText.Value = "Sen. Ron Johnson (R-WI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Jones, Doug", Range:=Selection.Range)
	oAutoText.Value = "Sen. Doug Jones (D-AL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Kaine, Tim", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tim Kaine (D-VA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Kennedy, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Kennedy (R-LA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="King, Angus", Range:=Selection.Range)
	oAutoText.Value = "Sen. Angus King (ID-ME)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Klobuchar, Amy", Range:=Selection.Range)
	oAutoText.Value = "Sen. Amy Klobuchar (D-MN)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Lankford, James", Range:=Selection.Range)
	oAutoText.Value = "Sen. James Lankford (R-OK)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Leahy, Patrick", Range:=Selection.Range)
	oAutoText.Value = "Sen. Patrick Leahy (D-VT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Lee, Mike", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mike Lee (R-UT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Manchin, Joe", Range:=Selection.Range)
	oAutoText.Value = "Sen. Joe Manchin (D-WV)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Markey, Edward", Range:=Selection.Range)
	oAutoText.Value = "Sen. Edward Markey (D-MA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="McConnell, Mitch", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mitch McConnell (R-KY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="McSally, Martha", Range:=Selection.Range)
	oAutoText.Value = "Sen. Martha McSally (R-AZ)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Menendez, Robert", Range:=Selection.Range)
	oAutoText.Value = "Sen. Robert Menendez (D-NJ)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Merkley, Jeff", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jeff Merkley (D-OR)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Moran, Jerry", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jerry Moran (R-KS)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Murkowski, Lisa", Range:=Selection.Range)
	oAutoText.Value = "Sen. Lisa Murkowski (R-AK)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Murphy, Christopher", Range:=Selection.Range)
	oAutoText.Value = "Sen. Christopher Murphy (D-CT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Murray, Patty", Range:=Selection.Range)
	oAutoText.Value = "Sen. Patty Murray (D-WA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Paul, Rand", Range:=Selection.Range)
	oAutoText.Value = "Sen. Rand Paul (R-KY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Perdue, David", Range:=Selection.Range)
	oAutoText.Value = "Sen. David Perdue (R-GA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Peters, Gary", Range:=Selection.Range)
	oAutoText.Value = "Sen. Gary Peters (D-MI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Portman, Rob", Range:=Selection.Range)
	oAutoText.Value = "Sen. Rob Portman (R-OH)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Reed, Jack", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jack Reed (D-RI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Risch, Jim", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jim Risch (R-ID)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Roberts, Pat", Range:=Selection.Range)
	oAutoText.Value = "Sen. Pat Roberts (R-KS)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Romney, Mitt", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mitt Romney (R-UT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Rosen, Jacky", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jacky Rosen (D-NV)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Rounds, Mike", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mike Rounds (R-SD)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Rubio, Marco", Range:=Selection.Range)
	oAutoText.Value = "Sen. Marco Rubio (R-FL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Sanders, Bernard", Range:=Selection.Range)
	oAutoText.Value = "Sen. Bernard Sanders (ID-VT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Sasse, Ben", Range:=Selection.Range)
	oAutoText.Value = "Sen. Ben Sasse (R-NE)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Schatz, Brian", Range:=Selection.Range)
	oAutoText.Value = "Sen. Brian Schatz (D-HI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Schumer, Charles", Range:=Selection.Range)
	oAutoText.Value = "Sen. Charles Schumer (D-NY)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Scott, Tim", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tim Scott (R-SC)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Scott, Rick", Range:=Selection.Range)
	oAutoText.Value = "Sen. Rick Scott (R-FL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Shaheen, Jeanne", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jeanne Shaheen (D-NH)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Shelby, Richard", Range:=Selection.Range)
	oAutoText.Value = "Sen. Richard Shelby (R-AL)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Sinema, Kyrsten", Range:=Selection.Range)
	oAutoText.Value = "Sen. Kyrsten Sinema (D-AZ)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Smith, Tina", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tina Smith (D-MN)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Stabenow, Debbie", Range:=Selection.Range)
	oAutoText.Value = "Sen. Debbie Stabenow (D-MI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Sullivan, Dan", Range:=Selection.Range)
	oAutoText.Value = "Sen. Dan Sullivan (R-AK)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Tester, Jon", Range:=Selection.Range)
	oAutoText.Value = "Sen. Jon Tester (D-MT)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Thune, John", Range:=Selection.Range)
	oAutoText.Value = "Sen. John Thune (R-SD)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Tillis, Thom", Range:=Selection.Range)
	oAutoText.Value = "Sen. Thom Tillis (R-NC)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Toomey, Patrick", Range:=Selection.Range)
	oAutoText.Value = "Sen. Patrick Toomey (R-PA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Udall, Tom", Range:=Selection.Range)
	oAutoText.Value = "Sen. Tom Udall (D-NM)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Van Hollen, Chris", Range:=Selection.Range)
	oAutoText.Value = "Sen. Chris Van Hollen (D-MD)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Warner, Mark", Range:=Selection.Range)
	oAutoText.Value = "Sen. Mark Warner (D-VA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Warren, Elizabeth", Range:=Selection.Range)
	oAutoText.Value = "Sen. Elizabeth Warren (D-MA)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Whitehouse, Sheldon", Range:=Selection.Range)
	oAutoText.Value = "Sen. Sheldon Whitehouse (D-RI)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Wicker, Roger", Range:=Selection.Range)
	oAutoText.Value = "Sen. Roger Wicker (R-MS)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Wyden, Ron", Range:=Selection.Range)
	oAutoText.Value = "Sen. Ron Wyden (D-OR)"
Set oAutoText = Templates(ActiveDocument.AttachedTemplate).AutoTextEntries.Add(Name:="Young, Todd", Range:=Selection.Range)
	oAutoText.Value = "Sen. Todd Young (R-IN)"
Set oAutoText = Nothing

End Sub
